name: Build

on:
  pull_request: 
    branches:
      - main
 
jobs:
  validate:
    name: Install, Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Package dependencies
        run: npm install

      # - name: Test
      #   run: npm run test

      - name: Build Package dependencies
        run: npm run build
